version: "2.15.1"

networks:
  rentx_net:
    driver: bridge

volumes:
  pgdata:
    driver: local

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    networks:
      - rentx_net
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    networks:
      - rentx_net
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database_rentx


